### PR TITLE
Added python phantom scraping doc sample

### PR DESCRIPTION
**Pull request by otherchirps**
Hi guys, here's a first draft for the python-phantom scraping doc page.

Happy to revise if you'd prefer different wording, or a more minimal example for the code chunk.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Lovely work @otherchirps, this reads well. I like the example with form entry and the window size tip too :star: I'm gonna test this out now.

**Comment by equivalentideas** [comment]
@otherchirps it's good that I'm testing this as I'm new to both python and phantomjs, so if we can make it so I can get it working it must be awesome ;-)

I added:

    splinter>=0.7.3

to requirements.txt, and then ran "pip install -r requirements.txt" (I think that step should be added in too)

Then I replaced the template scraper code with your example code. Then I run `python scraper.py`:

> python scraper.py                                                      
Traceback (most recent call last):
  File "scraper.py", line 3, in <module>
    with Browser("phantomjs") as browser:
  File "/usr/local/lib/python2.7/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/splinter/driver/webdriver/phantomjs.py", line 32, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 51, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/service.py", line 76, in start
    raise WebDriverException("Unable to start phantomjs with ghostdriver: %s" % e)
selenium.common.exceptions.WebDriverException: Message: Unable to start phantomjs with ghostdriver: [Errno 2] No such file or directory

Are there other dependencies I'm missing, or some advice we can give people if they get something like this?

**Comment by otherchirps** [comment]
Ah.  Yep.  Local testing... d'oh.  Assumed example running in morph-ish environment, where phantom is preinstalled.  

I'll add a section for that, including running / installing pip, and phantom.

**Comment by equivalentideas** [comment]
> including running / installing pip

Maybe that bit could link to the library docs somehow https://morph.io/documentation/libraries

**Comment by otherchirps** [comment]
Yep, sounds good. Will update tonight.

**Comment by otherchirps** [comment]
Pointed at the "Running scrapers on your own machine" page, since it runs through installing the whole pip + virtualenv + pip install -r requirements.txt dance already, so seemed to fit, I think.

Hopefully it's more clear than not. :)

**Comment by equivalentideas** [comment]
Hey @otherchirps that's helpful and I followed the steps to victory :) But then I realised we'd have the exact same issue with the Ruby instructions. so—

Do you think it would be clear if instead having the 'Testing locally' heading, the key sentence you've added gets moved into the page introduction. So the last sentence of the introduction could read something like (changes in bold):

> You can do this with PhantomJS which is essentially a headless browser that you can control from your scraper using JavaScript or a wrapper library. The PhantomJS binary, /usr/bin/phantomjs, is installed **on morph.io** as part of the phantomjs Ubuntu package which is installed in every scraper container as part of the build process. **To test a scraper with PhantomJS on your own machine, you'll need the to [download and install the binary](http://phantomjs.org/download.html) yourself.**

**Comment by otherchirps** [comment]
w00t!  Glad it worked.  And yes, moving that section makes complete sense.  This is why I shouldn't write docs after midnight. :)  Will update.

**Comment by otherchirps** [comment]
Hopefully that's a bit better.  Lost the "testing locally" section, as the important part is in the shared header now.  Thought it better to leave the local testing info up to the "/documentation/running_locally" page.  What do you reckon?

**Comment by equivalentideas** [comment]
:star2: :star2: :star2: 

Thanks @otherchirps ! Making the docs better is so important and helps everyone :)

I made a couple of changes you can see and picked up a typo ;-)

https://github.com/openaustralia/morph/compare/6af701cf2347...43b44ff09ec4

**Comment by otherchirps** [comment]
Sorry about the typos. Thanks for cleaning them up for me.  :-)

**Comment by equivalentideas** [comment]
> Sorry about the typos. Thanks for cleaning them up for me. :-)

No worries @otherchirps it happens to us all—[mostly me](https://github.com/openaustralia/planningalerts/commit/920369265a8eec226fc232c961df7dfd88054387).

**Pull request merged**
