### PR TITLE
Block all outgoing docker container traffic other than HTTP/HTTPS

### PR DESCRIPTION
**Pull request by henare**
Tested with https://github.com/morph-test-scrapers/port_test - the DNS lookup and HTTP request work and the telnet on port 666 fails.

### CODE REVIEW

**Comment by mlandauer** [comment]
I'm taking a look at this now

**Comment by mlandauer** [comment]
@henare Does the "-A DOCKER" only make these rules act on traffic from the docker containers?

**Comment by henare** [comment]
It means "append this to the DOCKER rule chain".

Communication from Docker containers arrives on the `docker0` interface and is sent to the DOCKER chain by a rule on the FORWARD chain. This means we can neatly apply rules to the DOCKER chain that only apply to Docker containers.

**Comment by mlandauer** [comment]
Nice. Thanks for the explanation!

**Comment by mlandauer** [comment]
I'll deploy to production now

**Comment by henare** [comment]
It took me so long to work all that out :dizzy_face: Easy when you know how.

**Comment by mlandauer** [comment]
Isn't that always the way? :-)

**Comment by mlandauer** [comment]
Looks to me like it's working in production: https://morph.io/morph-test-scrapers/port_test

Could you please double check @henare?

**Comment by henare** [comment]
LGTM! :+1:

**Comment by mlandauer** [comment]
We had some downtime overnight. I'm suspicious (though very far from certain) that the cause might be related to this change.

Yesterday in production i ran the script to remove the iptables rules and then ran the script to add them. I checked that the rules were in place by running `iptables-save` - it all looked fine. Then I tested it with @henare's test scraper and it all looked good... or so I thought.

This morning, I noticed that lots of scrapers have failed and things looked weird when I looked in scrapers and the connection_logs information was sometimes missing and also the console logs sometimes were blank even though it said it had run. Weird.

Anyway, I updated packages, rebooted the server. The docker server had to be started manually which is very weird - that of course could be the source of the problem.

Then, I ran `iptables-save` and got:

```
# Generated by iptables-save v1.4.12 on Sat Mar 28 12:03:54 2015
*security
:INPUT ACCEPT [38558:10984325]
:FORWARD ACCEPT [54:7412]
:OUTPUT ACCEPT [37355:19164832]
COMMIT
# Completed on Sat Mar 28 12:03:54 2015
# Generated by iptables-save v1.4.12 on Sat Mar 28 12:03:54 2015
*raw
:PREROUTING ACCEPT [38625:10995905]
:OUTPUT ACCEPT [37355:19164832]
COMMIT
# Completed on Sat Mar 28 12:03:54 2015
# Generated by iptables-save v1.4.12 on Sat Mar 28 12:03:54 2015
*nat
:PREROUTING ACCEPT [270:16145]
:INPUT ACCEPT [262:15534]
:OUTPUT ACCEPT [826:56464]
:POSTROUTING ACCEPT [826:56464]
:DOCKER - [0:0]
-A PREROUTING -i docker0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
-A PREROUTING -i docker0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 8080
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.17.0.2/32 -d 172.17.0.2/32 -p tcp -m tcp --dport 22 -j MASQUERADE
-A POSTROUTING -s 172.17.0.2/32 -d 172.17.0.2/32 -p tcp -m tcp --dport 80 -j MASQUERADE
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 2222 -j DNAT --to-destination 172.17.0.2:22
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 8000 -j DNAT --to-destination 172.17.0.2:80
COMMIT
# Completed on Sat Mar 28 12:03:54 2015
# Generated by iptables-save v1.4.12 on Sat Mar 28 12:03:54 2015
*mangle
:PREROUTING ACCEPT [38625:10995905]
:INPUT ACCEPT [38558:10984325]
:FORWARD ACCEPT [54:7412]
:OUTPUT ACCEPT [37363:19166960]
:POSTROUTING ACCEPT [37417:19174372]
COMMIT
# Completed on Sat Mar 28 12:03:54 2015
# Generated by iptables-save v1.4.12 on Sat Mar 28 12:03:54 2015
*filter
:INPUT ACCEPT [33280:9885160]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [32407:17152750]
:DOCKER - [0:0]
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 22 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
COMMIT
# Completed on Sat Mar 28 12:03:54 2015
```

I don't see the new rules to block docker traffic!

To sanity check here is the contents of `/etc/network/interfaces`:

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
post-up iptables-morph-add
```

and `/usr/local/sbin/iptables-morph-add` has as expected the new rules in it.

Anyway, for the moment it looks like the site is up and running again but it would be good to figure out in more detail what is going on here. It might be best to do that with a local test VM.

**Pull request merged**
