### PR TITLE
Routinely prune Docker

### PR DESCRIPTION
**Pull request by auxesis**
- We are running out of disk space on the Morph box every 1-2 days. 
- There is a [bug](http://github.com/openaustralia/morph/issues/1104) that is causing Docker to create a heap of AUFS diffs that don't get cleaned up. 
- Until we have the time and space to resolve that, we need some quick, automated bits to keep the pressure off disk space exhaustion. 
- This PR gets the Morph box running `docker system prune --all --force` every hour. 
- This should take the pressure down. 

[John Farnham – Pressure Down](https://www.youtube.com/watch?v=Emutat3_IP0)

### CODE REVIEW

**Comment by auxesis** [comment]
Have tested and run this against the Morph box. 

This PR is more a formality.

**Comment by auxesis** [comment]
Related to #1104.

**Comment by auxesis** [comment]
@henare @equivalentideas this is ready for your review.

**Comment by equivalentideas** [comment]
This looks pretty straight-forward to me, and it's already running in production. So I'll merge it 🚢 Thanks @auxesis 🌮

**Pull request merged**
