### PR TITLE
Mention JavaScript (Node) support

### PR DESCRIPTION
**Pull request by millette**
NodeJS supported according to https://github.com/openaustralia/morph/issues/791#issuecomment-115545090

### CODE REVIEW

**Comment by equivalentideas** [comment]
@millette nice one :+1: Is it important for javascript developers that Node/Phantom support is distinguished rather than just “javascript”?

**Comment by millette** [comment]
It's really two very different environments. I wasn't exactly sure how to put it, but since it was Perl, Python, PHP, I went ahead and added JavaScript as a language.

What's most important is that I basically skipped over morph since JavaScript (or NodeJS) wasn't mentionned in the README.

**Comment by equivalentideas** [comment]
> What's most important is that I basically skipped over morph since JavaScript (or NodeJS) wasn't mentionned in the README.

Thanks @millette that’s really helpful.

Are use using morph.io at morph.io or running your own instance? Did you come across it through it's Github repo? I'm interested because Node.js is listed on the homepage and documentation. Maybe we need to be paying more attention to the readme generally?

I also notice that our Node.js documentation is lacking (see the Node.js tab on this page https://morph.io/documentation/libraries). If you have time, filling that in a little could be another great way to help people writing Javascript scrapers ;-)

**Comment by millette** [comment]
Glad it helped. I haven't used morph yet. When I experiment more, I'll be back with a few patches, hopefully in March.

**Comment by equivalentideas** [comment]
> Glad it helped. I haven't used morph yet. When I experiment more, I'll be back with a few patches, hopefully in March.

Awesome thanks @millette :tropical_fish:

**Pull request merged**
