### PR TITLE
Small test fixes after updating buildstep

### PR DESCRIPTION
**Pull request by mlandauer**
This PR should **only** get merged at the same time as https://github.com/openaustralia/buildstep/pull/1

### CODE REVIEW

**Comment by mlandauer** [comment]
Note that the tests aren't expected to pass until the `openaustralia/buildstep` image has been updated from the PR https://github.com/openaustralia/buildstep/pull/1

**Comment by mlandauer** [comment]
To clarify comment ⬆️  the tests on travis-ci won't pass until the `openaustralia/buildstep` changes have been merged into master which will cause the `openaustralia/buildstep` image that is downloaded by travis to change.

For running the tests locally on this branch it should work fine as you long as your local image `openaustralia/buildstep` has been updated

**Comment by mlandauer** [comment]
Just pushed a small change to this branch (a merge from master actually) that should make the tests a little bit more reliable. @henare let's see if that makes a difference

**Comment by henare** [comment]
My [test suite is passing](https://github.com/openaustralia/buildstep/pull/1#issuecomment-237116085). Assigning back to you for merge and deploy.

**Pull request merged**
