### PR TITLE
[WIP] Add a tutorial on writing a simple scraper

### PR DESCRIPTION
**Pull request by equivalentideas**
Issue #421 

I've just plonked this in a markdown file while I'm writing it.

The dumb place for this to live is as another page in the documentation called “tutorial”. That's where I'm planning to park this for now. I'll have more of a think and ask for smarter ideas once there's a full draft.

### CODE REVIEW

**Comment by equivalentideas** [comment]
@henare could I get your feedback on the text of the  tutorial https://github.com/openaustralia/morph/blob/tutorial/app/views/documentation/tutorial.md

Anything that makes it clearer and easier to follow would be great. Flag bits that you think the reader needs a demonstration via gif or image.

There are places where I suspect it could be simplified. I want to get your thoughts on what can be cut before chopping.

Once we’re happy with the text I'll add it to the documentation section.

**Comment by henare** [comment]
@equivalentideas wow, this is huge!

I'm not in the right frame of mind to look at this right now so it'll take me a few days to get back to you with feedback. In the mean time it would be good to think about where we're going to put this.

**Comment by equivalentideas** [comment]
> I'm not in the right frame of mind to look at this right now so it'll take me a few days to get back to you with feedback.

No rush :+1:

> In the mean time it would be good to think about where we're going to put this.

I think as a section in the documentation could be a good spot. That way people looking for help/advice might see it.

dumping some thoughts about how we could link to this in the app :arrow_down: 

We could also include links to it in places where someone might need this kind of thing, such as when they first sign up or create a there first scraper. Lots of people sign up, create a scraper and then never edit it. This could be because they're interested, but don't know where to start. The tutorial could be one way to help them.

**Comment by henare** [comment]
Any more thoughts on where to put this @equivalentideas?

We've also discussed the following issues:

* It's Ruby-only and we don't want to give the impression morph.io is Ruby-only
* It's really big and so could be overwhelming. It would be good if we could break it up

However I really like the idea of linking off to it in the application (but being Ruby-only would be an issue).

We also discussed possibly posting this as a series of blog posts.

**Comment by henare** [comment]
As discussed with @equivalentideas we've decided to publish this as a blog post series. I've assigned it to me to extract posts and start posting them before we have our next scraping workshop.

**Comment by henare** [comment]
https://www.openaustraliafoundation.org.au/2015/10/13/ruby-web-scraping-tutorial-on-morph-io-part-1/

**Comment by henare** [comment]
https://www.openaustraliafoundation.org.au/2015/10/15/ruby-web-scraping-tutorial-on-morph-io-part-2-start-writing-your-scraper/

**Comment by henare** [comment]
I've scheduled the remaining posts to go out before the end of Thursday because @equivalentideas wanted to include them in the newsletter.

**Pull request closed without merging**
