### PR TITLE
Put in a logrotate for morph-app run out of Upstart

### PR DESCRIPTION
**Pull request by auxesis**
Discovered that upstart launching Morph had 1.3G of log files that weren't being rotated:

```
root@li421-88:/var/log# du -csh /var/log/morph/*.log
1020K   /var/log/morph/backtrace.log
4.6M    /var/log/morph/faye-1.log
110M    /var/log/morph/mitmproxy-1.log
616M    /var/log/morph/worker-1.log
592M    /var/log/morph/worker-2.log
1.3G    total
```

Some of the log entries go back to 2016-06. 

This PR puts a logrotate script in for morph-app running out of upstart.

### CODE REVIEW

**Comment by auxesis** [comment]
Have tested and run this against the Morph box. 

This PR is more a formality.

**Comment by auxesis** [comment]
Related to #1104.

**Comment by auxesis** [comment]
@henare @equivalentideas this is ready for your review.

**Comment by equivalentideas** [comment]
This looks good to me and is already running in production. So I'll merge it. Thanks you ⭐️ @auxesis :)

**Pull request merged**
