### PR TITLE
Limit scraper log lines to 50,000

### PR DESCRIPTION
**Pull request by henare**
This is a hacked together attempt at #919. It's not tested and doubtless
has plenty of problems.

Further caution: written while grumpy about a scraper backlog on
morph.io :rage:

This needs to be reviewed, tested, refined, and tests added.

### CODE REVIEW

**Comment by mlandauer** [comment]
This PR kills a job if it goes over a certain number of log lines. An alternative approach would be to somehow limit the number of log lines without actually killing the job. It would obviously need to still alert the user of this

**Comment by henare** [comment]
Let's close this since we're not actively working to merge this.

**Comment by mlandauer** [comment]
Hmmm. I think it's worth keeping open for the time being.

**Comment by mlandauer** [comment]
Given that I'm working on a different approach it does seem to make sense to me to close this now

**Pull request closed without merging**
