### PR TITLE
Use .shuffle to randomise list of heroes

### LINKED ISSUE #893: Randomise sort of heroes on front page
Right now it looks to be sorted by sign up date.

### PR DESCRIPTION
**Pull request by snoblenet**
Closes #893

### CODE REVIEW

**Comment by equivalentideas** [comment]
Nice one @snoblenet I've tested this and it works! :saxophone: :saxophone: :saxophone: 

I'm a little torn on whether to merge this, because the commit message doesn't provide any context about the change. It's really helpful to write _why_ a change was made in a commit message. The information of what was changed is in [the diff](https://github.com/openaustralia/morph/pull/976/commits/9f0dc13dedeaef600fdf851a460c20fe380bb541).

Here's a recent article on this idea I found useful: [The Art of the Commit](http://alistapart.com/article/the-art-of-the-commit) :)

In the future, when we run `git blame` or `git log` to understand why/how this line was changed, we won't get any clues from the current message. We’ll have to sleuth through Github to find it.

Because this is a small change I'm happy to merge this as is and you can just start adding more detailed commit messages in the future, or you could use `git amend` to add more explanation to this commit then force push to your branch here to change the commit.

What do you think?

**Comment by snoblenet** [comment]
Thanks for the link. Let me run a `git amend`, either today or tomorrow, depending on other commitments.

**Comment by equivalentideas** [comment]
Sounds good :+1:

**Comment by snoblenet** [comment]
I've had a look at a few of your recent public commits and you seem to prefer a single line in the present imperative -- correct?

**Comment by equivalentideas** [comment]
> I've had a look at a few of your recent public commits and you seem to prefer a single line in the present imperative -- correct?

Yeah, it's a command to the app: “Go do this” :) This one's not too bad (https://github.com/openaustralia/morph/commit/77756896e77b4df7ed833cc755285a837e423b20), single line then adding a bit more text _if need be_ after a line of white space.

**Comment by snoblenet** [comment]
Hi @equivalentideas -- does GitHub tell you automatically that I've pushed changes to this branch? I'm hoping it's read to merge into master.

**Comment by equivalentideas** [comment]
I've merged this locally @snoblenet because instead of amending the single commit with the change, you added two new commits. You can change an existing commit with `git commit --amend`. You would have then needed to force push to this branch to change the history here.

I used `cherry-picked` to grab the commit with the better message that had the change onto another branch without your other two commits.

https://github.com/openaustralia/morph/commit/13da9c80051404e56e746f3912e3abc9d779460c

Thanks for this contribution :star:

**Comment by snoblenet** [comment]
Thanks @equivalentideas -- all filed away in the grey matter now for future reference

**Comment by equivalentideas** [comment]
Deployed :tada:

**Pull request closed without merging**
