### PR TITLE
[WIP] Search banner for signed in landing page

### LINKED ISSUE #701: Add search banner to signed in landing page
extracted from #698 

**As a new user, when I sign up, I want to discover scrapers that are interesting to me, so I can better understand why scraping is useful and something I should learn more about.**

The best way we can currently help people find interesting scrapers is with search.

* [ ] Add a prominent search banner with some suggested search terms to get people started.
* [ ] Redirect new signups to this landing page, rather than their profile as we currently do.

Here's an idea for what the search banner form could be like:

Here's how this could sit in a banner on the page:

Maybe thinner, and maybe align the form more to the left of the page rather than centre.

It could be in our general banner style. Maybe a lighter or no background colour.

@mlandauer :
> I think some of those search examples should highlight scrapers for some of the non-english speaking countries where there are a lot of morph.io users (e.g. germany, spain) - it would also be good to include non-european examples I think.

### PR DESCRIPTION
**Pull request by equivalentideas**
To help citizens explore morph and discover scrapers of interest to them, these commits add a simple search form banner sections to the logged in landing page:

screen shot 2015-05-06 at 9 15 54 am
screen shot 2015-05-06 at 9 15 48 am

* [x] Before this is merged we need to settle on the suggested search terms (see [discussion on #701](https://github.com/openaustralia/morph/issues/701#issuecomment-99253000)).

relates to #698 

closes #701

### CODE REVIEW

**Comment by equivalentideas** [comment]
I'm also going to make the '2000 scrapers' dynamic, and ground to 100s, so it'll be 2200 now. That will give return users a nice sense of morph growing as the number increases.

**Comment by mlandauer** [comment]
Looks good.

I think just putting the number of scrapers there dynamically without any fancy rounding is fine.

Also might be nice to emphasise in some way that the scrapers have data which is what you're actually likely to be interested in here.

**Comment by mlandauer** [comment]
Or maybe you could say explicitly

> Search over 2134 scrapers for data you can use

**Comment by equivalentideas** [comment]
> I think just putting the number of scrapers there dynamically without any fancy rounding is fine.

I think here, where we want to get people excited to search, 'over 2200 scrapers', has that slight excitement where '2134 scrapers' feels a bit too accurate ;)

Happy to go with what you think though.

Trying out some variations of the 'for data you can use'.

**Comment by equivalentideas** [comment]
screen shot 2015-05-06 at 10 09 54 am

Here's a different approach with a pre-heading:
screen shot 2015-05-06 at 10 11 49 am

**Comment by mlandauer** [comment]
You're right. Giving the exact number takes some magic out of it. Go with your original idea of rounding to the hundreds.

**Comment by mlandauer** [comment]
I prefer the version with the preheading. Easier to scan and feels more human.

**Comment by equivalentideas** [comment]
> I prefer the version with the preheading. Easier to scan and feels more human.

Yeah I quite like that too. Happy with that text? 'Find data and code you can use' or maybe 'Find data and code to use'. I think mentioning the "you" in there somehow is nice.

**Comment by equivalentideas** [comment]
I can't get [number_to_rounded()](http://www.rubydoc.info/docs/rails/4.0.0/ActiveSupport/NumberHelper:number_to_rounded) to work for some reason.

In consol I get:

> number_to_rounded(111.2345, precision: 1, significant: true)
> NoMethodError: undefined method `number_to_rounded' for main:Object

**Comment by mlandauer** [comment]
Here's a trick to make that work. The function you're trying to call is a
view helper so is normally only available in views. To be able to access
those in the console you need to do a little bit of a trick (which is also
the same trick you use for calling them in tests) which is to call them
through a `helper` object. So, specifically,

```
helper.number_to_rounded(111.2345, precision: 1, significant: true)
```

**Comment by equivalentideas** [comment]
Thanks @mlandauer , now I'm getting:

> helper.number_to_rounded(111.2345, precision: 1, significant: true)
> NoMethodError: undefined method `number_to_rounded' for #<ActionView::Base:0x000001014ca660>

It's like it just isn't defined for some reason :S.

I pushed the pre-header:

screen shot 2015-05-06 at 10 52 35 am

**Comment by mlandauer** [comment]
Sorry I should have tested it for myself. You'll need to include the correct library. So in the console,
```
> include ActiveSupport::NumberHelper
 => Object
> helper.number_to_rounded(111.2345, precision: 1, significant: true)
 => "100"
```

**Comment by mlandauer** [comment]
@equivalentideas how do you feel about extracting the search box out into a partial and then using that same partial on the main search page?

**Comment by equivalentideas** [comment]
I think that's a good idea. In that case maybe only show the suggested terms if there's no query.

**Comment by mlandauer** [comment]
Not showing the suggested terms when there's a query is an excellent idea!

**Comment by equivalentideas** [comment]
@mlandauer I still can't get the number rounding to work somehow, following your tip I can get it in consol, but when I add it to the view I get 'undefined method `number_to_rounded' for #<#<Class:0x000001016526e0>:0x000001014e3610>' :S

**Comment by equivalentideas** [comment]
I'll extract that partial now.

**Comment by mlandauer** [comment]
Weird. `number_to_rounded` is not defined as a view helper. It's just in `ActiveSupport`. I feel like I'm missing something

**Comment by equivalentideas** [comment]
@mlandauer do you think we need to make some change to the heading text to include users on the search page?

screen shot 2015-05-06 at 11 32 44 am

**Comment by mlandauer** [comment]
@equivalentideas that sounds like a very good idea. Something that could everywhere?

**Comment by mlandauer** [comment]
@equivalentideas can you push a commit to just extract the partial. So I can make the change for the number of scrapers?

**Comment by equivalentideas** [comment]
@mlandauer done with 816d91b

**Comment by equivalentideas** [comment]
> @equivalentideas that sounds like a very good idea. Something that could work everywhere?

Maybe '

Find data and code you can use
Search over 2200 scrapers and users

**Comment by mlandauer** [comment]
I think that wording has lots of ambiguity and it might get a little too longwinded to word it unambiguously. So, maybe we should pull the heading out of the partial and go back to having different headings on those different pages but stick with the common search box and suggested searches?

**Comment by equivalentideas** [comment]
What do you think about?

screen shot 2015-05-06 at 11 53 03 am

adds a little wrap on very small screens, but not a problem I don't think:

screen shot 2015-05-06 at 11 51 13 am

**Comment by mlandauer** [comment]
Unless we change the heading to
> Search over 2200 scrapers and 2000 users

Does that work or is that too long winded?

**Comment by equivalentideas** [comment]
I think too long and we go with your suggestion of going back to the separate headings "Search over 2200 scrapers" and just "Search" on the search page.

> So, maybe we should pull the heading out of the partial and go back to having different headings on those different pages but stick with the common search box and suggested searches?

It might be simpler to do the heading text as an option on the partial, because it's actually the label for the form input, so we'd be losing functionality by pulling it out of the partial because we couldn't make it the label anymore. Does that make sense?

**Comment by equivalentideas** [comment]
I just noticed the search banner form input has the same input as the header search. That's a problem as it's invalid markup and also could confuse assistive tech.

**Comment by mlandauer** [comment]
How about this?

We pull the subheading out of the partial and make the partial just show "search" as the heading but you can optionally override it with your own text that you pass to the partial.

That way the partial stays generic and doesn't get tied into the specific wording and implementation of the search box on the landing page.

Does that make sense?

**Comment by equivalentideas** [comment]
Yep. And would we pass the subheading through the option?

**Comment by mlandauer** [comment]
The subheading would get pulled out of the partial and put just back on the landing page template

**Comment by equivalentideas** [comment]
> The subheading would get pulled out of the partial and put just back on the landing page template

That's gonna require a bit of css rejig to get that to work and it'll be less semantically grouped html, with part of the heading/form label outside of the form block. Feels wrong, maybe not sharing the partial would be simpler? I'm not sure.

**Comment by mlandauer** [comment]
Okay, another solution (which would be my preferred option) as it's the simplest would be to use a separate generic label which just says "Search" and which is only visible to screen readers. Then, the heading (and the sub-heading) can be moved above the form and out of the partial and we can go back to having separate headings on those two pages.

**Comment by equivalentideas** [comment]
> Okay, another solution (which would be my preferred option) as it's the simplest would be to use a separate generic label which just says "Search" and which is only visible to screen readers. Then, the heading (and the sub-heading) can be moved above the form and out of the partial and we can go back to having separate headings on those two pages.

I can live with that. Having a little more complex markup for simpler code. I'll move the 'banner' wrapper stuff and the headings out of the partial, and rename it the search form partial :)

**Comment by equivalentideas** [comment]
just going to rename that partial and do a small refactor

**Comment by equivalentideas** [comment]
I think this is ready to go @mlandauer

**Pull request merged**
