### PR TITLE
Distinguish and add more explanation to dangerous settings

### PR DESCRIPTION
**Pull request by equivalentideas**
Why:

@tmtmtmtm summarises the issue well:

> Both of these [the **clear database** and **delete scraper** options] look the same, are in essentially the same place, and have largely identical "are you sure" popups, but the effects of one are rather more severe than the other.
>
> At least twice now I've managed to completely delete a scraper rather than just emptying it because my brain has no short-cuts to differentiating between them and I wasn't paying sufficient attention.

Basically these's so little distinction between the two options that they’re easy to confuse. I also think that aside from the characteristically fun “Here be dragons”, the button text and alert is quite cold.

Making these options more distinguishable helps people avoid deleting their scraper accidentally, and making the options more understandable helps people use them more effectively. 

This PR:

* Move's the important 'these can't be undone' message above the buttons
* Adds more text to explain and distinguish the options
* Uses the text-left buttons-right pattern—familiar from Github—to slow the user down and get the to consider more.
* Makes the text friendlier, more conversational and human overall.

While on #886 it was suggested we just change the buttons colour or layout, when I looked at it, I really felt more text, explanation and a human touch was needed for starts. I think this also distinguishes the options.

## Before:

screen shot 2015-08-28 at 10 44 12 am
screen shot 2015-08-28 at 10 44 23 am

## After:

screen shot 2015-08-28 at 10 43 55 am
screen shot 2015-08-28 at 10 44 49 am

Any thoughts feedback @tmtmtmtm ?

### CODE REVIEW

**Comment by equivalentideas** [comment]
Assigning to @henare for review next week.

**Comment by tmtmtmtm** [comment]
These will almost certainly still have the same problems for me. Although they're better explained etc., and thus presumably better for new users, I already _know_ exactly what both do, and still occasionally hit the wrong one — because I'm *not* stopping to carefully read things every time I visit the page. Trying to make users who think they already know what they're doing read the text isn't really the problem. You'll get much better results by giving more points of obvious differentiation — i.e. visually distinguishing by something other than text.

**Comment by henare** [comment]
@equivalentideas I agree with @tmtmtmtm, assigning back to you to see if you can address those points.

**Comment by equivalentideas** [comment]
Sorry it's taken me so long to get back around to this! :rabbit:

> These will almost certainly still have the same problems for me. Although they're better explained etc., and thus presumably better for new users, I already know exactly what both do, and still occasionally hit the wrong one — because I'm not stopping to carefully read things every time I visit the page. Trying to make users who think they already know what they're doing read the text isn't really the problem. You'll get much better results by giving more points of obvious differentiation — i.e. visually distinguishing by something other than text.

@tmtmtmtm thanks for this is really great feedback. I agree that while the changes in this PR make the controls more understandable for new users, they don't do much people who've used them before. It's easy to make a slip and click the other button that looks so similar.

To help prevent these errors, I'll try visually distinguishing the buttons with colour ( as you suggested in #886 ).

**Comment by equivalentideas** [comment]
I've used colour here to distinguish the buttons. I think this is working better now. @tmtmtmtm Do you think now that the buttons are different colours, and shapes, you'd avoid the error you were having?

screen shot 2016-03-29 at 10 55 03 am

**Comment by jpmckinney** [comment]
What about putting a ☠ in the "Delete your scraper" button text?

**Comment by equivalentideas** [comment]
Here's a quick mock of some icons, just using the inbuilt bootstrap stuff. That skull emoji is more fun :confetti_ball: but do the illustrations help?

screen shot 2016-04-05 at 10 28 26 am

**Comment by tmtmtmtm** [comment]
These are definitely big improvements on what's live at the minute. 

There may be further gains to be made later, but with the icons we now have two points of differentiation, which I'd say is enough of a win to go with this and see if it helps. :shipit:

**Comment by equivalentideas** [comment]
> There may be further gains to be made later, but with the icons we now have two points of differentiation, which I'd say is enough of a win to go with this and see if it helps. :shipit:

Awesome, thanks for that @tmtmtmtm ( and also @jpmckinney ).

I'll implement the icons and review the code and :shipit: if all good.

**Comment by CloCkWeRX** [comment]
One idle though: Github's delete repository behaviour might be a good example to look at: "Type the name of the scraper to confirm you understand it will be deleted." if the UI changes aren't quite enough by themselves

**Comment by equivalentideas** [comment]
> One idle though: Github's delete repository behaviour might be a good example to look at: "Type the name of the scraper to confirm you understand it will be deleted." if the UI changes aren't quite enough by themselves

Totally @CloCkWeRX :+1: We'll see how this goes and can try something else/more like that if the unintentional deletes continue to happen.

**Comment by equivalentideas** [comment]
Deployed :ship: Thanks for your help @tmtmtmtm @jpmckinney @CloCkWeRX @henare

**Pull request merged**
