### PR TITLE
Landing page branch rebase master

### PR DESCRIPTION
**Pull request by equivalentideas**
This is the `new_landing_page` branch after a rebase from `origin\master` to bring it up to date.

I did this because the server would not start on my local machine in this branch which was 238 commits behind.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Maybe it would be better to make this a new branch rather than do the merge?

**Comment by mlandauer** [comment]
So did you do a rebase or a merge here @equivalentideas?

**Comment by equivalentideas** [comment]
Sorry I was using 'merge' to mean I resolved the conflicts. I ran `git rebase origin/master` which then ran into conflicts as it re ran the commits. I resolved those conflicts as it prompted me to. Is that what you were after?

**Comment by mlandauer** [comment]
Okay, the general rule is *never* do a rebase on a branch that's been published because it changes history. Only ever merge. When you're working on a private local branch (on your development machine for example) it's totally fine to do a rebase - in fact it's good - in order to maintain a clean history.

So, throw this branch away (I'll close the PR), and start again. Do the following:
* Create a new branch off of the main openaustralia/new_landing_page branch
* *merge* the master branch into your new_landing_page branch - that takes all the changes made on master and merges them into your local branch
* This can then be used to create a PR against openaustralia/new_landing_page

**Comment by equivalentideas** [comment]
Great, thanks for the instructions :)

**Pull request closed without merging**
