### PR TITLE
[WIP] Notice and documentation that downloads are public

### PR DESCRIPTION
**Pull request by equivalentideas**
We want to give users some notice and explain why we're showing their data download activity.

This PR adds a small notice to the scraper page (next to the download links) and API docs page. It also adds a new section to the documentation about this feature.

I think think notices could be in an into alert style of some kind, gonna try that. Feed back on that and on the text would be much appreciated.

Here's the text file https://github.com/openaustralia/morph/blob/downloader-notice/app/views/documentation/_open_downloads.md

### CODE REVIEW

**Comment by equivalentideas** [comment]
I've added a notice style to the notices to make them more prominent and because we use that style for other notices on the site, so we're building up a familiar pattern:

screen shot 2015-05-07 at 5 13 43 pm
screen shot 2015-05-07 at 5 13 55 pm

**Comment by mlandauer** [comment]
I think the alert pattern is good. On the API page I think it's now too prominently placed and the more I think about it, it should go further down the page because the first part of that page is just explaining how to use the api and it just muddles that if it's put where it is now.

Perhaps it should go just above the example?

**Comment by mlandauer** [comment]
I'm having a go at the documentation wording now. It might take me a bit to get into the swing of it.

**Comment by equivalentideas** [comment]
> Perhaps it should go just above the example?

Between the params and example sections? That seems right as even if you're not using the example it's very clear. I always get confused on that page as to what's the bit you use ( #710 ).

**Comment by equivalentideas** [comment]
I'm just committing an improvement to the alert layout css on above the data-table.

**Comment by mlandauer** [comment]
@equivalentideas yes, between the params and example section

**Comment by mlandauer** [comment]
@equivalentideas now that I think of it, based on what you said in #710, maybe that's not the best place. Oh never mind, let's not worry about it and deal with #710 soon and then come back to this

**Comment by equivalentideas** [comment]
> let's not worry about it and deal with #710 soon and then come back to this

That sounds good :+1: .

**Comment by equivalentideas** [comment]
Should I still move it down for now?

**Comment by equivalentideas** [comment]
In making the layout more stable I also just adding a little space about the 'sign in to download' stuff for signed out users:

## Before
screen shot 2015-05-07 at 5 36 40 pm

## After
screen shot 2015-05-07 at 5 36 26 pm

**Comment by mlandauer** [comment]
I don't know. It's not obvious to me where it should go right now. What do you think?
> Should I still move it down for now?

**Comment by equivalentideas** [comment]
It's still quite clear moved down:
screen shot 2015-05-07 at 5 41 01 pm

Some people (particularly small screens) will need to scroll. Hmmm. Maybe we should lean to more obvious for now and not move it.

**Comment by mlandauer** [comment]
Would it be too cheesy to add a lightbulb icon to the alert? http://fortawesome.github.io/Font-Awesome/icon/lightbulb-o/

**Comment by equivalentideas** [comment]
> Would it be too cheesy to add a lightbulb icon to the alert?

I'm not sure if it's the right icon. I think first pass just text.

**Pull request merged**
