### PR TITLE
Added Capybara, Pry and related gems for feature specs and debugging

### PR DESCRIPTION
**Pull request by snoblenet**
Doesn't close any particular issue today, but does set us up to close many of them in the future

### CODE REVIEW

**Comment by henare** [comment]
Nice! @snoblenet did you also have a test you wanted to add? It seems odd merging this when we're not using it for anything yet.

**Comment by snoblenet** [comment]
Yes the PRs I submit for #969 #320 etc will all include feature specs using Capybara.

**Comment by henare** [comment]
On the basis of getting nice tests for those other PRs I'm happy to merge this :smile: However you closed it, was that intentional?

**Comment by snoblenet** [comment]
Sorry. Github.com UI confusion. I forgot the discussion was inside a pull, not an issue, and therefore that hitting Close & Comment would close the PR.

**Comment by henare** [comment]
Thanks @snoblenet! :rocket:

**Pull request merged**
