### PR TITLE
[For Review] Add User search

### LINKED ISSUE #507: Add search over people
By handle / name. Related to #103

### PR DESCRIPTION
**Pull request by equivalentideas**
This adds search over users and splits search results into two pages, one for Scrapers and one for Users.

One big TODO that I couldn't work out a good way to do.
* [ ] add organisations into the user results.

I thought this could be done in the [`static_controller`](https://github.com/openaustralia/morph/blob/e2e3bcbf44e78f54839ee32442370f1f44fb4d79/app/controllers/static_controller.rb) by setting `@users` to be `User.search(@q)` merged with `Organisation.search(@q)`, but I couldn't work out how to do that and for some reason it felt like a bad idea. @mlandauer could you show me the light or pick that bit up please?

closes #507 

screen shot 2015-04-21 at 8 19 23 pm
screen shot 2015-04-21 at 8 19 33 pm

### CODE REVIEW

**Comment by mlandauer** [comment]
@equivalentideas I added the search over organisations and fixed a couple of small bugs. Each commit is doing only one thing. It would be really useful for you, I think, to go through this commit by commit and make sure you understand what each bit is doing. Any questions, just ask!

**Comment by equivalentideas** [comment]
Thanks for that @mlandauer that's really helpful. Some very nice changes there like https://github.com/openaustralia/morph/commit/f56b00a06652f225c66355c80a9aa7a97b8bd578

Why did you move search to it's own controller?

**Comment by mlandauer** [comment]
controllers should be grouping related actions together. It was fairly arbitrary before that it was in the same controller as the landing page. So, made more sense to give its own controller

**Comment by equivalentideas** [comment]
ah awesome, thanks.

**Pull request merged**
